"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Triangle = exports.Square = exports.Rectangle = exports.Circle = exports.Shape = void 0;
var Shape_1 = require("./Shape");
Object.defineProperty(exports, "Shape", { enumerable: true, get: function () { return Shape_1.default; } });
var Circle_1 = require("./Circle");
Object.defineProperty(exports, "Circle", { enumerable: true, get: function () { return Circle_1.default; } });
var Rectangle_1 = require("./Rectangle");
Object.defineProperty(exports, "Rectangle", { enumerable: true, get: function () { return Rectangle_1.default; } });
var Square_1 = require("./Square");
Object.defineProperty(exports, "Square", { enumerable: true, get: function () { return Square_1.default; } });
var Triangle_1 = require("./Triangle");
Object.defineProperty(exports, "Triangle", { enumerable: true, get: function () { return Triangle_1.default; } });
