"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Student = exports.Group = exports.Level = exports.Direction = exports.School = void 0;
var School_1 = require("./School");
Object.defineProperty(exports, "School", { enumerable: true, get: function () { return School_1.default; } });
var Direction_1 = require("./Direction");
Object.defineProperty(exports, "Direction", { enumerable: true, get: function () { return Direction_1.default; } });
var Level_1 = require("./Level");
Object.defineProperty(exports, "Level", { enumerable: true, get: function () { return Level_1.default; } });
var Group_1 = require("./Group");
Object.defineProperty(exports, "Group", { enumerable: true, get: function () { return Group_1.default; } });
var Student_1 = require("./Student");
Object.defineProperty(exports, "Student", { enumerable: true, get: function () { return Student_1.default; } });
